### ISSUE TITLE
To avoid UserWarning and allow choice of databases

### ISSUE THREAD

**Issue by ReveredEye** [zwang2019/BetTube_Project_0#1]
Use `pip install SQLAlchemy`
I have used `SQLconfig` instead of `conf`
and separated `configs` into dictionary of 'driver', 'server',... instead of just 'db'
You're going to have to readjust below to work with your conf.py file
------------Code below ---------

from sqlalchemy import create_engine
from sqlalchemy.engine import URL

def conn_str(database = SQLconfig.configs['database']):
    details = ('DRIVER=%s;'
            'SERVER=%s;'
            'DATABASE=%s;'
            'UID=%s;'
            'PWD=%s;' % (SQLconfig.configs['driver'], SQLconfig.configs['server'],
                database, SQLconfig.configs['uid'], SQLconfig.configs['pwd']))
    return(details)

connection_string = conn_str()
connection_url = URL.create("mssql+pyodbc", query={"odbc_connect": connection_string})
engine = create_engine(connection_url)

**Comment by zwang2019** [comment]
Thanks for fixing this
